name: "Test - action"

on: 
  push:

jobs:
  unit-test:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v2
    - name: Use Node.js LTS
      uses: actions/setup-node@v1
      with:
        node-version: '14.x'
    - uses: bahmutov/npm-install@v1
    - name: Build
      run: yarn run build
    - name: Unit Tests
      run: yarn run test
      env:
        CI: true
